# Generated by Django 5.2.1 on 2025-05-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['-submitted_at']},
        ),
    ]
