# Generated by Django 5.2 on 2025-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formresponse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
